### ISSUE TITLE
Closing sections in experimental ember 2.0 UI

### ISSUE THREAD

**Issue by erlinghoff** [joachimhs/Contentice#4]
When a section is opened by clicking on the drop-down triangle, clicking that triangle again should minimize the section. Now, it stays open. See screenshot. Tested in Safari.

![skjermbilde 2016-03-02 kl 12 33 02](https://cloud.githubusercontent.com/assets/4093630/13459416/b53cea56-e073-11e5-9423-54c523efed2a.png)

**Comment by joachimhs** [comment]
Fixed in commit b625b77881a7628df4cb0ca9468658a0ccfdc342
