### ISSUE TITLE
Unable to delete a subcategory in the left nav bar - experimental ember 2.0 UI

### ISSUE THREAD

**Issue by erlinghoff** [joachimhs/Contentice#5]
Nothing happens when the button is pressed:

![skjermbilde 2016-03-02 kl 15 46 57](https://cloud.githubusercontent.com/assets/4093630/13463834/6ec38b78-e08e-11e5-87f2-3dcad1cd929d.png)

**Comment by joachimhs** [comment]
Fixed in commit 2c2cc63ad80a9368f03e09b4ca7add3fc4d96236. 

Requires deploy of both frontend and backend to work
